---
- name: Agent Relay host | Reload systemd after runner unit change
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: agent_relay_host reload runner systemd unit

- name: Agent Relay host | Restart containerd after configuration change
  ansible.builtin.systemd_service:
    name: containerd.service
    enabled: true
    state: restarted
  listen: agent_relay_host restart containerd

- name: Agent Relay host | Stop Docker before socket change
  ansible.builtin.systemd_service:
    name: docker.service
    state: stopped
  listen: agent_relay_host restart Docker socket

- name: Agent Relay host | Reload systemd and restart Docker socket
  ansible.builtin.systemd_service:
    name: docker.socket
    enabled: true
    daemon_reload: true
    state: restarted
  listen: agent_relay_host restart Docker socket

- name: Agent Relay host | Start Docker after socket change
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: true
    state: started
  listen: agent_relay_host restart Docker socket

- name: Agent Relay host | Restart Docker after configuration change
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: true
    state: restarted
  listen: agent_relay_host restart Docker
